version: 2.1
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
        name: docker-compose build
        command: docker-compose up --build -d
      - run:
        name: create db
        command: docker-compose exec --env 'RAILS_ENV=test' web rails db:create
      - run:
        name: create tables
        command: docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
      - run:
        name: test
        command: docker-compose exec --env 'RAILS_ENV=test' web bin/rspec
