version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.8-node-browsers
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: ruby test
          command: bin/rspec
